version: '3.8'

services:
    nginx:
      restart: always
      build:
        dockerfile: Dockerfile
        context: ./nginx
      depends_on:
      - server
      ports:
      - 80:80  
    server:
      build:
        dockerfile: Dockerfile
        context: ./
      restart: always
      volumes:
        - ./:/usr/src/app
        - /usr/src/app/node_modules
      ports:
        - 8081:8081